name: GIT-SYNC

on:
  push:
    branchs:
      - "feature/*"

jobs:
  syncGHtoGHE:
    runs-on: ubuntu-latest
    environment:
      name: PAT
    timeout-minutes: 15
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          # source_repo: "https://zhang-m:${{ secrets.PAT }}@github.jp.klab.com/zhang-m/migration-test.git"
          source_repo: "zh-ml/migration"
          source_branch: "$GITHUB_REF"
          # destination_repo: "zh-ml/migration"
          destination_repo: "https://zhang-m:${{ secrets.PAT }}@github.jp.klab.com/zhang-m/migration-test.git"
          destination_branch: "$GITHUB_REF"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`